### ISSUE TITLE
How is this different from CrossOver?

### ISSUE THREAD

**Issue by GirkovArpa** [5R33CH4/OneShot#2]
It looks identical to [this](https://github.com/lacymorrow/crossover)?

**Comment by monke0192** [comment]
> It looks identical to [this](https://github.com/lacymorrow/crossover)?

It isn't different. It's literally just the same project, just an older version and blatantly copied.

**Comment by 5R33CH4** [comment]
> It looks identical to [this](https://github.com/lacymorrow/crossover)?

Indeed, But it has 320+ new overlays [which crossover lacks]
